name:                adventofcode
version:             0.1.0.0
github:              "karandit/adventofcode"
license:             BSD3
author:              "Kárándi Tamás"
maintainer:          "example@example.com"
copyright:           "2020 Kárándi Tamás"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: [range, containers, MissingH, array, vector, primitive, regex-applicative]

    #executables:
    #  adventofcode-exe:
    #    main:                Main.hs
    #    source-dirs:         app
    #    ghc-options:
    #    - -threaded
    #    - -rtsopts
    #    - -with-rtsopts=-N
    #    dependencies: [adventofcode, containers, MissingH]

tests:
  tasty-test:
    main:                AllSpec.hs
    source-dirs:         test/unittests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: [adventofcode, tasty, tasty-hunit]
  doc-test:
    main:                DocTest.hs
    source-dirs:         test/doctests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: [adventofcode, doctest]
