on: [push]
name: build
jobs:
  runhaskell:
    name: Haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: '2.7.3'
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('haskell/stack.yaml.lock') }}-${{ hashFiles('haskell/package.yaml') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('haskell/stack.yaml.lock') }}-
          path: ~/haskell/.stack
      - run: |
          cd haskell
          stack test

  runidris:
    name: Idris2
    runs-on: ubuntu-latest
    container: mattpolzin2/idris-docker:0.5.1
    steps:
      - uses: actions/checkout@v2
      - name: Run Idris2 golden tests
        run: |
          cd idris
          idris2 --install adventofcode.ipkg
          idris2 --build adventofcode-tests.ipkg
