on: [push]
name: build
jobs:
  runhaskell:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
